Import Required Libraries

In [1]:
# Import Pandas
import pandas as pd

Load the CSV File

In [2]:
# Load the dataset
df = pd.read_csv("SuperMarket Analysis.csv")

# Display the first 5 rows
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [16]:
# Rename columns for better readability
df.rename(columns={
    "Sales": "Revenue",
    "cogs": "Expense",
    "gross income": "Profit",
    "Customer type": "Customer_Type",
    "Product line": "Product_Line",
    "Unit price": "Unit_Price",
    "Invoice ID": "Transaction_ID",
    "Tax 5%": "Tax"
}, inplace=True)

# Display updated column names
print(df.columns.tolist())

['Transaction_ID', 'Branch', 'City', 'Customer_Type', 'Gender', 'Product_Line', 'Unit_Price', 'Quantity', 'Tax', 'Revenue', 'Date', 'Time', 'Payment', 'Expense', 'gross margin percentage', 'Profit', 'Rating']

Check the Dataset Structure

In [3]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [4]:
# Display the number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (1000, 17)

In [5]:
# Display data types
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

Display Missing Values

In [6]:
# Check missing values
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

Remove Duplicate Transaction IDs

In [7]:
# Count duplicate Invoice IDs
print("Duplicate Invoice IDs:", df["Invoice ID"].duplicated().sum())

Duplicate Invoice IDs: 0

In [8]:
# Remove duplicate Invoice IDs
df = df.drop_duplicates(subset="Invoice ID")

# Verify duplicates are removed
print("Duplicate Invoice IDs After Cleaning:", df["Invoice ID"].duplicated().sum())

Duplicate Invoice IDs After Cleaning: 0

Handle Missing Revenue and Expense Values

In [12]:
# Fill missing values in Sales (Revenue)
df["Sales"] = df["Sales"].fillna(df["Sales"].median())

# Fill missing values in cogs (Expense)
df["cogs"] = df["cogs"].fillna(df["cogs"].median())

# Verify missing values
df[["Sales", "cogs"]].isnull().sum()

Sales    0
cogs     0
dtype: int64

In [11]:
print(df.columns.tolist())

['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date', 'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income', 'Rating']

Remove Currency Symbols and Convert to Numeric

In [13]:
# Remove currency symbols and commas from Sales
df["Sales"] = (
    df["Sales"]
    .astype(str)
    .str.replace(r"[$₹,]", "", regex=True)
)

# Convert Sales to numeric
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")

In [14]:
# Remove currency symbols and commas from cogs
df["cogs"] = (
    df["cogs"]
    .astype(str)
    .str.replace(r"[$₹,]", "", regex=True)
)

# Convert cogs to numeric
df["cogs"] = pd.to_numeric(df["cogs"], errors="coerce")

In [15]:
print(df[["Sales", "cogs"]].dtypes)

Sales    float64
cogs     float64
dtype: object

Convert the Date Column

In [17]:
# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

In [18]:
print(df["Date"].dtype)

datetime64[ns]

Verify the Cleaned Dataset

In [19]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Transaction_ID           1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer_Type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product_Line             1000 non-null   object
 6   Unit_Price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax                      1000 non-null   float64
 9   Revenue                  1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  Expense                  1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  Profit                   1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [20]:
# Missing values
df.isnull().sum()

Transaction_ID             0
Branch                     0
City                       0
Customer_Type              0
Gender                     0
Product_Line               0
Unit_Price                 0
Quantity                   0
Tax                        0
Revenue                    0
Date                       0
Time                       0
Payment                    0
Expense                    0
gross margin percentage    0
Profit                     0
Rating                     0
dtype: int64

In [21]:
# First five rows
df.head()

,Transaction_ID,Branch,City,Customer_Type,Gender,Product_Line,Unit_Price,Quantity,Tax,Revenue,Date,Time,Payment,Expense,gross margin percentage,Profit,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [22]:
# First five rows
df.head()

,Transaction_ID,Branch,City,Customer_Type,Gender,Product_Line,Unit_Price,Quantity,Tax,Revenue,Date,Time,Payment,Expense,gross margin percentage,Profit,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [23]:
# Statistical summary
df.describe()

,Unit_Price,Quantity,Tax,Revenue,Date,Expense,gross margin percentage,Profit,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,2019-02-14 00:05:45.600000,307.58738,4.761905e+00,15.379369,6.97270
min,10.080000,1.000000,0.508500,10.678500,2019-01-01 00:00:00,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,2019-01-24 00:00:00,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,2019-02-13 00:00:00,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,2019-03-08 00:00:00,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,2019-03-30 00:00:00,993.00000,4.761905e+00,49.650000,10.00000
std,26.494628,2.923431,11.708825,245.885335,NaN,234.17651,6.131498e-14,11.708825,1.71858

Save the Cleaned Dataset

In [24]:
# Save cleaned dataset
df.to_csv("SuperMarket_Analysis_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!